//インスタンスリスト
var idata = {
	"kirishima.cloud": "instance",
	"kirishima.cloud_name": "アスタルテ",
	"kirishima.cloud_letters": "6229",
	"kirishima.cloud_bbcode": "enabled",
	"kirishima.cloud_markdown": "enabled",
	"kirishima.cloud_glitch": "enabled",
	"kirishima.cloud_public": "パブリックタイムライン",
	"minohdon.jp": "instance",
	"minohdon.jp_name": "箕面どん",
	"fedibird.com":"instance",
	"fedibird.com_name":"Fedibird",
	"fedibird.com_quote":"enabled",
	"mastodos.com": "instance",
	"mastodos.com_name": "マストどす",
	"dev.kirishima.cloud": "hidden",
	"dev.kirishima.cloud_name": "アスタルテ(Dev)",
	"dev.kirishima.cloud_letters": "6229",
	"dev.kirishima.cloud_bbcode": "enabled",
	"dev.kirishima.cloud_markdown": "enabled",
	"dev.kirishima.cloud_glitch": "enabled",
	"mstdn.y-zu.org": "instance",
	"mstdn.y-zu.org_name": "Yづドン(Y-zuDon)",
	"imastodon.net": "instance",
	"imastodon.net_name": "im@stodon",
	"imastodon.net_home": "オフィス",
	"imastodon.net_local": "楽屋",
	"imastodon.net_notification": "ホワイトボード",
	"imastodon.net_public": "ライブステージ",
	"imastodon.net_post": "あふぅ",
	"imastodon.net_fav": "の頭にティンときたようです",
	"imastodon.net_bt": ":「わかるわ」",
	"imastodon.net_follow": "名刺をいただきました",
	"mstdn.osaka_home": "ウチ",
	"mstdn.osaka_local": "近所",
	"mstdn.osaka_notification": "あめちゃん",
	"mstdn.osaka_public": "新世界",
	"mstdn.osaka_post": "なんや！",
	"mstdn.osaka_fav": "がええやん言いました",
	"mstdn.osaka_bt": "がしばいた",
	"mstdn.osaka_follow": "ツルまれました",
	"mstdn.kemono-friends.info": "instance",
	"mstdn.kemono-friends.info_name": "ますとどんちほー",
	"mstdn.kemono-friends.info_letters": "1024",
	"mstdn.kemono-friends.info_home": "なわばり",
	"mstdn.kemono-friends.info_local": "ますとどんちほー",
	"mstdn.kemono-friends.info_notification": "ねえねえ!",
	"mstdn.kemono-friends.info_public": "ジャパリパーク",
	"mstdn.kemono-friends.info_post": "がおー！",
	"mstdn.kemono-friends.info_fav": ":「すごーい」",
	"mstdn.kemono-friends.info_bt": ":「たーのしー」",
	"itabashi.0j0.jp": "instance",
	"itabashi.0j0.jp_name": "板橋丼",
	"itabashi.0j0.jp_letters": "1024",
	"itabashi.0j0.jp_quote":"enabled",
	"dtp-mstdn.jp": "instance",
	"dtp-mstdn.jp_name": "dtp-mstdn.jp",
	"dtp-mstdn.jp_quote":"enabled",
	"misskey.io": "misskey",
	"misskey.io_name": "misskey.io",
	"misskey.io_letters": "1000",
	"misskey.io_bbcode": "disabled",
	"misskey.io_markdown": "enabled",
	"misskey.io_public": "Global",
	"misskey.io_post": "Post",
	"misskey.io_fav": " reacted your post.",
	"misskey.io_bt": " reposted your post.",
	"misskey.dev": "misskey",
	"misskey.dev_name": "misskey.dev",
	"misskey.dev_letters": "1024",
	"misskey.dev_bbcode": "disabled",
	"misskey.dev_markdown": "enabled",
	"misskey.dev_public": "Global",
	"misskey.dev_post": "Post",
	"misskey.dev_fav": " reacted your post.",
	"misskey.dev_bt": " reposted your post.",
	"precure.ml": "instance",
	"precure.ml_name": "キュアスタ！",
	"precure.ml_letters": "1024",
	"precure.ml_post": "キュア！",
	"odakyu.app_quote":"enabled",
	"nitiasa.com_quote":"enabled",
	"biwakodon.com_quote":"enabled",
	"comm.cx_quote":"enabled"
};

localStorage.setItem("instance", JSON.stringify(idata));
