# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: macOS build

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: macos-latest
    environment:
      name: build
    env: 
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      CSC_LINK: ${{ secrets.CSC_LINK}}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: sudo sntp -sS time.windows.com
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd app && yarn
    - run: cd app && yarn build:all
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "build/*.zip"
    - uses: shogo82148/actions-upload-release-asset@v1
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "build/*.dmg"